/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

import * as Circuits from ".";

declare module "hardhat/types/runtime" {
  interface HardhatZKit {
    getCircuit(name: "Matrix", protocol: "groth16"): Promise<Circuits.Matrix>;
    getCircuit(name: "NoInputs", protocol: "groth16"): Promise<Circuits.NoInputs>;
  }
}
